const PickyuqLocaleEn = {
  wlWaitingRestauranConfirm: 'Waiting for the restaurant to confirm',
  wlOrderPrepared: 'Your order is being prepared',
  wlOrderPickupDriver: 'Order is ready to pickup by driver',
  wlOrderOnTheWay: 'Order is on the way to your place',
  wlOrderPrepared: 'Your order is being prepared',
  wlNoOngoingOrder: 'Seem’s like there is no ongoing order ...',
  btnLetMakeOrder: 'Let’s make an order',
  wlPleaseWait: 'Please Wait ...',
  pTypeMessage: 'Type message...',
  wlWaitRestauran:
    'Your order was sent to the restaurant. Waiting for the restaurant to confirm your order',
  wlCancelOrder: 'Cancel Order',
  wlOrderPreparing: 'Your order is preparing',
  wlNudgingNearbyDriver: 'Nudging nearby driver',
  wlDeliveryDetails: 'Delivery details',
  wlRestaurantLocation: 'Restaurant location',
  wlDeliveryLocation: 'Delivery location',
  wlTotalPayment: 'Total Payment',
  wlDontSpicy: 'Dont spicy',

  wlYuqGohere: 'Where do you want to go ?',
  HLastDesti: 'Last Destination',
  wlShowMap: 'Show Map',
  HPickyuqUser: 'Pickup Location',
  wlConfirmPickUser: 'Confirm Pickup Location',
  HpickupWhere: 'Where do we pickup?',
  wlSelectOnMap: 'Choose from maps',
  wlLocationNow: 'Current location',
  HDestinationUser: 'Destination Location',
  wlConfirmDestinationUser: 'Confirm Destination Location',
  wlOrderNow: 'Order now',
  wlFindDriver: 'Looking for Drivers',
  wlDetailPayment: 'Payment detail',
  wlTripPrice: 'Trip price',
  wlTotalPayment: 'Total payment',
  wlPaymentMethod: 'Paymen method',
  wlnoVoucher: 'No vouchers',
  wlAddRate: 'Rate for drivers',
  wlTipDriver: 'Are you going to tip the driver?',
};

const PickyuqLocaleId = {
  wlWaitingRestauranConfirm: 'Menunggu konfirmasi dari resto',
  wlOrderPrepared: 'Pesananmu sedang disiapkan',
  wlOrderPickupDriver: 'Pesananmu udah siap, kami carikan Driver ya',
  wlOrderOnTheWay: 'Order is on the way to your place Pesananmu sedang diantar',
  wlOrderPrepared: 'Pesananmu sedang disiapkan',
  wlNoOngoingOrder: 'Belum ada pesanan apapun nih',
  btnLetMakeOrder: 'Yuq, pesan menu favoritmu!',
  wlPleaseWait: 'Tunggu sebentar ya...',
  pTypeMessage: 'Ketik disini...',
  wlWaitRestauran:
    'Pesananmu sudah diteruskan ke resto. Tunggu mereka konfirmasi pesananmu ya',
  wlCancelOrder: 'Batalkan Pesanan',
  wlOrderPreparing: 'Pesananmu sedang disiapkan',
  wlNudgingNearbyDriver: 'Kami carikan Driver untuk antar pesananmu...',
  wlDeliveryDetails: 'Detail Pengantaran',
  wlRestaurantLocation: 'Lokasi Restoran',
  wlDeliveryLocation: 'Lokasi Pengantaran',
  wlTotalPayment: 'Total Pembayaran',
  wlDontSpicy: 'Tidak pedas',

  wlYuqGohere: 'Ingin pergi kemana ?',
  HLastDesti: 'Tujuan Terakhir',
  wlShowMap: 'Lihat Peta',
  HPickyuqUser: 'Lokasi Penjemputan',
  wlConfirmPickUser: 'Konfirmasi Lokasi Penjemputan',
  HpickupWhere: 'Kita Jemput dimana?',
  wlSelectOnMap: 'Pilih dari map',
  wlLocationNow: 'Lokasi saat ini',
  HDestinationUser: 'Lokasi Tujuan',
  wlConfirmDestinationUser: 'Konfirmasi Lokasi Tujuan',
  wlOrderNow: 'Pesan sekarang',
  wlFindDriver: 'Sedang Mencari Driver',
  wlDetailPayment: 'Detail pembayaran',
  wlTripPrice: 'Harga perjalanan',
  wlTotalPayment: 'Total pembayaran',
  wlPaymentMethod: 'Metode pembayaran',
  wlnoVoucher: 'Tidak ada voucher',
  wlAddRate: 'Beri rating untuk driver',
  wlTipDriver: 'Apakah anda akan memberi tip kepada driver?',
};

export {PickyuqLocaleEn, PickyuqLocaleId};
