const HomeLocaleEn = {
  exploreInputPlaceholder: 'Find something good to eat',
  deliverTo: 'Deliver To',
  myBalance: 'My Balance',
  myBalanceDana: 'My Dana',
  topUp: 'Top up',
  history: 'History',
  verifyYourEmail:
    'Verify your email to enable account recovery if there are problems with logging in,',
  verifyNow: 'Verify Now',
  nearMe: 'Near Me',
  promo: 'Promos',
  bestSeller: 'Best Seller',
  fastFood: 'Fast Food',
  fullTimeHours: '24 Hours',
  newResto: 'New Resto',
  hNew: 'New',
  healtyFood: 'Healthy Food',
  allCuisine: 'All Cuisines',
  rateYourOrder: 'Rate your order',
  recomendedForYou: 'Recommended for you',
  orderWithVoucher: 'Order with voucher',
  orderAgain: 'Order Again',
  yuqOrder: 'Yuq, reorder!',
  mostLikedFood: 'Most liked food',
  popularInArea: 'Popular in your area',
  topRatedHayuqer: 'Top rated by Hayuqers',
  giveRating: 'Give rating',
  rateTheDriver: 'Rate the driver',
  seeAll: 'see all',
  voucherFromRestaurant: 'Get vouchers to order from these restaurants',
  promotion: 'Promotion',
  yuqReorder: 'Yuq, reorder!',
  chooseFoodReorder: `Choose any food you'd like to reorder`,
  restaurantNearby: `Check out today's most ordered restaurant nearby!`,
  orders: 'Orders',
  backToTop: 'Back to top',
  chooseTopupMethod: 'Choose top up method',
  yourPayyuqBalance: 'Your Payyuq Balance',
  search: 'Search',
  pEnterNameRestaurant: 'Enter restaurant name',
  pEnterNameDish: 'Enter dish name',
  hRecentSearch: 'Recent search',
  hSearchCuisines: 'Search in cuisines',
  wlShare: 'Share',
  wlOutofStock: 'Out of stock',
  wlNotes: 'Notes',
  wlOptional: 'Optional',
  wlRequire: 'Required',
  pExampleMoreSauce: 'Example: add more sauce plz',
  btnAddtoCart: 'Add to cart',
  btnEdittoCart: 'Edit to cart',
  wlAddtoFavorite: 'Added to favorites',
  wlRatings: 'ratings',
  hRatings: 'Ratings',
  lhRatings: 'rating',
  wlDistance: 'Distance',
  wlFoodLikes: 'Food likes',
  wlCloseAt: 'Close at',
  wlVoucherAvailable: 'Voucher Available',
  wlViewall: 'View all',
  wlSold: 'sold',
  wlLikes: 'likes',
  wlVouchers: 'Vouchers',
  wlIniDia: 'INI DIAA',
  lAdd: 'Add',
  Hmenu: 'Menu',
  wlItem: 'item',
  Hcart: 'Cart',
  pAddNotes: 'Add a notes...',
  lCheckout: 'Checkout',
  wlPromoItem: 'Promo item',
  wlAbout: 'About',
  wlOpeningHours: 'Opening Hours',
  wlAddress: 'Address',
  wlMyFavorites: 'My favorites',
  wlDishes: 'dishes',
  wlAdddishesYourFavorites: 'Add dishes to your favorites',
  wlNewFavorite: 'New favourite',
  hAwesomedishes: 'Awesome dishes',
  hDeletethisList: 'Delete this list?',
  dDelletethisList: 'All item at this favorites will be deleted also.',
  hEditListDetail: 'Edit favorite list detail’s',
  wlFavoritesName: 'Favorites name',
  wlMakscharacter: 'Maks character',
  hCreateFavoriteList: 'Create new favorite list',
  lCreate: 'Create',
  lSaveChange: 'Save Changes',
  lCancel: 'Cancel',
  lYesDelete: 'Yes, Delete',
  hHayuqPartner: 'Hayuq Partner',
  wlClosed: 'Closed.',
  wlOpenAt: 'Open at',
  wlArabic: 'Arabic',
  wlRestaurantCuisines: 'restaurant in this cuisines',
  wlOngoingPromos: 'ongoing promos',
  wlYourLastOrderRestaurant: 'Your last order from restaurant',
  wlFailedGetLocation:
    'We can’t find this place on the map. Check your input or choose the location from map',
  wlChaoiceMap: 'Choose from Map',
  wlMyLocation: 'My current location',
  wlSelectMap: 'Select on map',
  wlSavedAddress: 'Saved Address',
  wlManage: 'Manage',
  wlFrequentlyUsed: 'Frequently used',
  wlNoData: 'No Data',
  wlDeliveryLocation: 'Delivery location',
  wlAddNote: 'Add Note',
  wlOrderSummary: 'Order Summary',
  wlPaymentDetails: 'Payment Details',
  wlIsEnough: 'Is it enough?',
  wlAddOtherDishes: 'Add other dishes, if you want it.',
  wlUseVoucherOrder: 'Use voucher before order',
  wlVoucherApplied: 'Voucher applied',
  wlPaymentMethod: 'Payment Method',
  wlChange: 'Change',
  wlEdit: 'Edit',
  wlFromYou: 'from you',
  wlChoosePaymentMethod: 'Choose payment method',
  btnChoosePaymentMethod: 'Choose as payment method',
  wlNoData: "doesn't have item, please try another one",
};

const HomeLocaleId = {
  exploreInputPlaceholder: 'Yuq, cari makanan kesukaanmu',
  deliverTo: 'Antar ke',
  myBalance: 'Saldo Payyuq',
  myBalanceDana: 'Saldo Dana',
  topUp: 'Top up',
  history: 'Riwayat Pesanan',
  verifyYourEmail:
    'Verifikasi emailmu, yuq. Untuk memudahkan pemulihan akun saat terjadi kendala.',
  verifyNow: 'Verifikasi Sekarang',
  nearMe: 'Di sekitar sini',
  promo: 'Promo',
  bestSeller: 'Paling Laris',
  fastFood: 'Fast Food',
  fullTimeHours: 'Buka 24 Jam',
  newResto: 'Restoran Baru',
  hNew: 'New',
  healtyFood: 'Menu Sehat',
  allCuisine: 'Ragam menu',
  rateYourOrder: 'Rate pesanan ini',
  recomendedForYou: 'Rekomendasi buatmu',
  orderWithVoucher: 'Pesan pakai voucher',
  orderAgain: 'Order Lagi',
  yuqOrder: 'Yuq, pesan lagi!',
  mostLikedFood: 'Menu paling disukai',
  popularInArea: 'Populer di area ini',
  topRatedHayuqer: 'Favorit Sahabat Hayuq',
  giveRating: 'Kasih rating',
  rateTheDriver: 'Rate Driver',
  seeAll: 'Lihat',
  voucherFromRestaurant: 'Ambil voucher sebelum pesan di resto ini',
  promotion: 'Promosi',
  yuqReorder: 'Yuq, pesan lagi!',
  chooseFoodReorder: `Pilih menu yang mau kamu pesan lagi`,
  restaurantNearby: `Lihat menu yang paling banyak dipesan di area ini`,
  orders: 'Pesanan',
  backToTop: 'Kembali ke laman atas',
  chooseTopupMethod: 'Pilih top up pakai apa',
  yourPayyuqBalance: 'Saldo Payyuq Balance-ku',
  search: 'Cari',
  pEnterNameRestaurant: 'Ketik nama resto',
  pEnterNameDish: 'Ketik nama menu',
  hRecentSearch: 'Terakhir dicari',
  hSearchCuisines: 'Cari di ragam menu',
  wlShare: 'Bagikan',
  wlOutofStock: 'Sudah habis',
  wlNotes: 'Catatan',
  wlOptional: 'Opsional',
  wlRequire: 'Perlu diisi',
  pExampleMoreSauce: 'Contoh: tidak pedas yaa',
  btnAddtoCart: 'Tambah ke keranjang',
  btnEdittoCart: 'Edit ke keranjang',
  wlAddtoFavorite: 'Ditambahkan ke menu favorit',
  wlRatings: 'rating',
  hRatings: 'Rating',
  lhRatings: 'rating',
  wlDistance: 'Jarak',
  wlFoodLikes: 'Likes',
  wlCloseAt: 'Tutup jam',
  wlVoucherAvailable: 'Voucher tersedia',
  wlViewall: 'Lihat',
  wlSold: 'Habis terjual',
  wlLikes: 'likes',
  wlVouchers: 'Voucher',
  wlIniDia: 'INI DIAA',
  lAdd: 'Tambah',
  Hmenu: 'Menu',
  wlItem: 'item',
  Hcart: 'Keranjang',
  pAddNotes: 'Tambah catatan...',
  lCheckout: 'Checkout',
  wlPromoItem: 'Menu Promo',
  wlAbout: 'Tentang',
  wlOpeningHours: 'Jam buka',
  wlAddress: 'Alamat',
  wlMyFavorites: 'Menu Favoritku',
  wlDishes: 'Ragam makanan',
  wlAdddishesYourFavorites: 'Tambah ini ke Menu Favorit',
  wlNewFavorite: 'Menu Favorit Baru',
  hAwesomedishes: 'Makanan Enak',
  hDeletethisList: 'Hapus list ini?',
  dDelletethisList: 'Semua item menu di list ini bakal dihapus juga.',
  hEditListDetail: 'Edit detail list Favorit',
  wlFavoritesName: 'Nama List',
  wlMakscharacter: 'Maks. karakter',
  hCreateFavoriteList: 'Buat list baru',
  lCreate: 'Buat',
  lSaveChange: 'Simpan',
  lCancel: 'Batal',
  lYesDelete: 'Ya, hapus',
  hHayuqPartner: 'Mitra UMKM Hayuq',
  wlClosed: 'Tutup.',
  wlOpenAt: 'Buka jam',
  wlArabic: 'Arabic',
  wlRestaurantCuisines: 'Resto yang jual ragam makanan ini',
  wlOngoingPromos: 'Promo yang lagi berlangsung',
  wlYourLastOrderRestaurant: 'Menu terakhir yang dipesan dari resto ini',
  wlFailedGetLocation:
    'Wah, lokasi ini gak ketemu di map. Coba cek ulang alamatnya atau pilih titik lokasinya dari map.',
  wlChaoiceMap: 'Pilih dari map',
  wlMyLocation: 'Lokasiku sekarang',
  wlSelectMap: 'Pilih di map',
  wlSavedAddress: 'Alamat tersimpan',
  wlManage: 'Atur',
  wlFrequentlyUsed: 'Sering Digunakan',
  wlNoData: 'Gak ada data',
  wlDeliveryLocation: 'Lokasi Pengantaran',
  wlAddNote: 'Tulis Catatan',
  wlOrderSummary: 'Ringkasan Pesanan',
  wlPaymentDetails: 'Detail Pembayaran',
  wlIsEnough: 'Ini aja pesanannya?',
  wlAddOtherDishes: 'Bisa tambah menu lain kalau mau',
  wlUseVoucherOrder: 'Pakai voucher sebelum pesan',
  wlVoucherApplied: 'Voucher terpakai',
  wlPaymentMethod: 'Metode Pembayaran',
  wlChange: 'Ubah',
  wlEdit: 'Edit',
  wlFromYou: 'darimu',
  wlChoosePaymentMethod: 'Pilih metode pembayaran',
  btnChoosePaymentMethod: 'Pilih sebagai metode pembayaran',
  wlNoData: 'Tidak memiliki data, silakan coba pilihan lain',
};

export {HomeLocaleEn, HomeLocaleId};
