import {StyleSheet, Platform} from 'react-native';
import {dimensions} from '@config/Platform.config';
import {CustomSpacing, Colors, Rounded, Fonts} from '@styles';

const styles = () => {
  return StyleSheet.create({
    restaurantContainer: {
      flex: 1,
      backgroundColor: Colors.backgroundSurface,
    },
    imgProfileBg: {
      width: dimensions.screenWidth,
      height: dimensions.screenWidth * 0.4,
    },
    actionPosition: {
      position: 'absolute',
      bottom: dimensions.screenWidth * 0.15,
      paddingHorizontal: CustomSpacing(16),
      justifyContent: 'space-between',
      width: dimensions.screenWidth,
    },
    actionContainer: {
      width: CustomSpacing(40),
      height: CustomSpacing(40),
      backgroundColor: Colors.neutral10,
      borderRadius: CustomSpacing(40),
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerContainerRestaurant: {
      position: 'absolute',
      top: -CustomSpacing(30),
      left: CustomSpacing(16),
      backgroundColor: Colors.neutral10,
      borderRadius: Rounded.xl,
      width: dimensions.screenWidth - CustomSpacing(32),
      shadowColor: '#20252ad9',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
    },
    imgAvatar: {
      width: CustomSpacing(80),
      height: CustomSpacing(80),
      borderRadius: CustomSpacing(80),
      backgroundColor: Colors.neutral10,
      position: 'absolute',
      top: -CustomSpacing(20),
      left: CustomSpacing(16),
      borderWidth: 1,
      borderColor: Colors.neutral40,
    },
    detailContainer: {
      backgroundColor: Colors.neutral20,
      borderBottomLeftRadius: Rounded.xl,
      borderBottomRightRadius: Rounded.xl,
      paddingHorizontal: CustomSpacing(16),
      justifyContent: 'space-between',
      paddingVertical: CustomSpacing(8),
    },
    ratingContainer: {
      backgroundColor: Colors.primaryMain,
      borderRadius: Rounded.xl,
      paddingHorizontal: CustomSpacing(10),
      paddingVertical: CustomSpacing(2),
      justifyContent: 'center',
      alignItems: 'center',
    },
    separatorDetail: {
      width: 1,
      height: CustomSpacing(50),
      backgroundColor: Colors.neutral40,
    },
    totalLikesContainer: {
      backgroundColor: Colors.supportMain,
      borderRadius: Rounded.xl,
      paddingHorizontal: CustomSpacing(10),
      paddingVertical: CustomSpacing(2),
      justifyContent: 'center',
      alignItems: 'center',
    },
    contentContainer: {
      padding: CustomSpacing(16),
    },
    voucherContainer: {
      padding: CustomSpacing(16),
      backgroundColor: Colors.neutral10,
      borderRadius: Rounded.xl,
      width: dimensions.screenWidth - CustomSpacing(32),
      shadowColor: '#20252ad9',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
      justifyContent: 'space-between',
    },
    viewAllIcon: {
      width: CustomSpacing(21),
      height: CustomSpacing(21),
      backgroundColor: Colors.secondarySurface,
      borderRadius: CustomSpacing(40),
      justifyContent: 'center',
      alignItems: 'center',
    },
    titlePromo: {
      padding: CustomSpacing(8),
      borderBottomWidth: 1,
      borderBottomColor: Colors.neutral50,
      borderStyle: Platform.OS === 'ios' ? 'solid' : 'dashed',
    },
    promoCard: {
      backgroundColor: Colors.neutral10,
      padding: CustomSpacing(8),
      maxWidth: CustomSpacing(133),
      borderRadius: Rounded.l,
      shadowColor: '#20252ad9',
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
    },
    imgPromoIcon: {
      width: CustomSpacing(117),
      height: CustomSpacing(117),
      borderRadius: Rounded.l,
    },
    actionBarParalaxContainer: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? -CustomSpacing(140) : -CustomSpacing(120),
      backgroundColor: Colors.neutral10,
      width: '100%',
      paddingHorizontal: CustomSpacing(16),
      paddingVertical: CustomSpacing(8),
    },
    renderSectionContainer: {
      paddingVertical: CustomSpacing(16),
      borderBottomColor: Colors.neutral40,
    },
    renderVoucherContainer: {
      paddingVertical: CustomSpacing(12),
      paddingHorizontal: CustomSpacing(28),
      marginHorizontal: CustomSpacing(16),
      marginTop: CustomSpacing(10),
      // borderBottomColor: Colors.neutral40,
      // backgroundColor: '#2f333780',
    },
    bottomVoucherContainer: {
      paddingVertical: CustomSpacing(12),
      paddingHorizontal: CustomSpacing(28),
      marginHorizontal: CustomSpacing(25),
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    imgRenderSection: {
      width: CustomSpacing(86),
      height: CustomSpacing(86),
      borderRadius: Rounded.l,
    },
    // --- Restaurant Detail ---
    imgAvatarDetail: {
      width: CustomSpacing(80),
      height: CustomSpacing(80),
      borderRadius: CustomSpacing(80),
      backgroundColor: Colors.neutral10,
      position: 'absolute',
      top: -CustomSpacing(20),
      left: dimensions.screenWidth / 2 - CustomSpacing(56),
      borderWidth: 1,
      borderColor: Colors.neutral40,
    },
    // --- Search Food ---
    searchFoodContainer: {
      backgroundColor: Colors.backgroundSurface,
    },
    headerContainer: {
      padding: CustomSpacing(16),
      backgroundColor: Colors.neutral10,
    },
    searchContainer: {
      backgroundColor: Colors.neutral40,
      borderRadius: Rounded.xl,
      paddingHorizontal: CustomSpacing(16),
    },
    textInputStyle: {
      ...Fonts.labelSemiBold,
      color: Colors.neutral70,
      height: CustomSpacing(50),
      width: '70%',
    },
    searchInput: {
      ...Fonts.labelSemiBold,
      color: Colors.neutral70,
      height: CustomSpacing(50),
      width: '100%',
    },
    // ------ |||| ------
    // ------ Filter ------
    containerCard: {
      paddingHorizontal: CustomSpacing(8),
      paddingVertical: CustomSpacing(4),
      borderRadius: Rounded.xl,
      alignItems: 'center',
      justifyContent: 'center',
    },
    containerFilter: {
      paddingHorizontal: CustomSpacing(16),
      paddingVertical: CustomSpacing(4),
      borderRadius: Rounded.xl,
      marginRight: CustomSpacing(4),
      marginBottom: CustomSpacing(4),
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    imgChevronDown: {
      width: CustomSpacing(12),
      height: CustomSpacing(12),
    },
    containerClearFilter: {
      borderColor: Colors.dangerMain,
      paddingHorizontal: CustomSpacing(16),
      paddingVertical: CustomSpacing(4),
      borderRadius: Rounded.xl,
      marginRight: CustomSpacing(4),
      marginBottom: CustomSpacing(4),
      backgroundColor: Colors.neutral10,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    // ------ |||| ------
    imgVoucherInfo: {
      marginVertical: CustomSpacing(12),
      marginHorizontal: CustomSpacing(16),
      height: dimensions.screenWidth * 0.2,
    },
    imgVoucherCard: {
      height: dimensions.screenWidth * 0.4,
      // marginVertical: CustomSpacing(12),
    },
    imgVoucherEatyuq: {
      height: 50,
      width: 50,
    },
    imgVoucherTimer: {
      height: 16,
      width: 16,
    },
    ratingSeparator: {
      width: 1,
      height: CustomSpacing(100),
      backgroundColor: Colors.neutral50,
    },
    dashedSeparator: {
      borderBottomColor: Colors.neutral90,
      borderBottomWidth: 1,
      marginVertical: CustomSpacing(16),
      width: dimensions.screenWidth * 0.9,
      borderStyle: Platform.OS === 'ios' ? 'solid' : 'dashed',
    },
    btnPlus: {
      padding: CustomSpacing(6),
      width: CustomSpacing(28),
      height: CustomSpacing(28),
      borderRadius: CustomSpacing(28),
      backgroundColor: Colors.primaryMain,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnMinus: {
      padding: CustomSpacing(6),
      width: CustomSpacing(28),
      height: CustomSpacing(28),
      borderRadius: CustomSpacing(28),
      backgroundColor: Colors.primarySurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnMenuParalax: {
      backgroundColor: Colors.secondaryMain,
      width: CustomSpacing(128),
      paddingHorizontal: CustomSpacing(16),
      paddingVertical: CustomSpacing(5),
      borderRadius: CustomSpacing(100),
    },
    btnCart: {
      backgroundColor: Colors.primaryMain,
      width: dimensions.screenWidth - CustomSpacing(32),
      borderRadius: Rounded.m,
      paddingVertical: CustomSpacing(6),
      paddingHorizontal: CustomSpacing(20),
      justifyContent: 'space-between',
    },
    headerCartModal: {
      justifyContent: 'space-between',
      paddingBottom: CustomSpacing(16),
      borderBottomWidth: 1,
      borderBottomColor: Colors.neutral40,
    },
    containerItem: {
      paddingVertical: CustomSpacing(16),
      borderBottomWidth: 1,
      borderBottomColor: Colors.neutral40,
    },
    btnMinusCartModal: {
      padding: CustomSpacing(6),
      width: CustomSpacing(20),
      height: CustomSpacing(20),
      borderRadius: CustomSpacing(20),
      backgroundColor: Colors.primarySurface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnPlusCartModal: {
      padding: CustomSpacing(2),
      width: CustomSpacing(20),
      height: CustomSpacing(20),
      borderRadius: CustomSpacing(20),
      backgroundColor: Colors.primaryMain,
      alignItems: 'center',
      justifyContent: 'center',
    },
    qtyCartModal: {
      padding: CustomSpacing(2),

      height: CustomSpacing(32),
      borderRadius: CustomSpacing(20),
      backgroundColor: Colors.primaryMain,
    },
    menuListModal: {
      backgroundColor: Colors.neutral10,
      marginVertical: CustomSpacing(16),
      padding: CustomSpacing(16),
      width: dimensions.screenWidth - CustomSpacing(32),
      borderRadius: CustomSpacing(12),
      shadowColor: Colors.supportSurface,
      shadowOffset: {
        width: 0,
        height: 3,
      },
      shadowOpacity: 0.27,
      shadowRadius: 4.65,
      elevation: 6,
    },
    // ------ Navigation Bar  ------
    NavigatorContainer: {
      justifyContent: 'space-between',
      padding: CustomSpacing(16),
      backgroundColor: Colors.neutral10,
    },
    imgCloseIcon: {
      width: CustomSpacing(24),
      height: CustomSpacing(24),
      resizeMode: 'contain',
    },
    discountCountainer: {
      width: CustomSpacing(68),
      backgroundColor: Colors.supportSurface,
      borderRadius: Rounded.xl,
      paddingHorizontal: CustomSpacing(10),
      paddingVertical: CustomSpacing(2),
    },
    // --------- Modal Closed Restaurant Style ---------
    backgroundModal: {
      backgroundColor: '#000',
      position: 'absolute',
      width: dimensions.screenWidth,
      height: dimensions.screenHeight,
      opacity: 0.3,
      zIndex: 10,
    },
    buttonModal: {
      backgroundColor: Colors.dangerMain,
      position: 'absolute',
      zIndex: 20,
      width: dimensions.screenWidth,
      bottom: 0,
      paddingVertical: 20,
    },
    textButtonModal: {
      ...Fonts.subhead,
      textAlign: 'center',
      color: '#fff',
    },
  });
};

export default styles;
