export default {
  translation: {
    hHistoryOrder: 'Riwayat Pesanan',
    wlReorder: 'Pesan Lagi',
    wlRateRestaurant: 'Kasih rate resto ini',
    wlYourReview: 'Review Darimu',
    wlNoReview: 'Belum ada review',
    wlHowWasYourFood: 'Puas sama pesananmu?',
    wlYourRating: 'Rating Darimu',
    wlNoOrder: 'Belum ada pesanan apapun nih ...',
    wlFoodDelivery: 'Pesan-antar makanan',
    wlOrder: 'Pesan',
    wlRateRestaurant: 'Yuq, rate resto ini',
    wlTeelUs: 'Kasih tau kami gimana pesananmu & resto ini',
    wlThakyouForRate: 'Terima kasih udah kasih rate!',
    wlDeliveryDetails: 'Detail Pengantaran',
    wlRestauranLocation: 'Lokasi Resto',
    wlDeliveryLocation: 'Lokasi Pengantaran',
    hOrdersummary: 'Ringkasan Pesanan',
    wlPaymentDetails: 'Detail Pembayaran',
    wlSubTotal: 'Subtotal',
    wlDeliveryFee: 'Ongkos kirim',
    wlServiceOtherFees: 'Biaya lainnya',
    wlDiscounts: 'Diskon',
    wlTotalPayment: 'Total Pembayaran',
    wlPayment: 'Pembayaran',
    wlTellUsMore: 'Ada komentar tambahan?',
    pNoteRate:
      'Lorem ipsum dolor sit amet consectetur. Nec vel egestas risus placerat lobortis magna. Sed sollicitudin sed commodo proin mus.',
    wlHideMyName: 'Sembunyikan namaku saat review',
    wlHowDelivery: 'Bagaimana pengirimannya?',
    wlNoFound: 'Data tidak ditemukan',
  },
};
